package io.github.monthalcantara.ApiEstudoDynamoDb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.io.Serializable;

/**
 * @DynamoDBTable Essa annotation diz para o Spring Data que essa classe será uma tabela
 * */
@DynamoDBTable(tableName = "Costumer")
@Getter
@Setter
public class Costumer implements Serializable {
    /**
     * @Id:  Essa annotation diz para o Spring Data que esse atributo deve será um identificador da tabela.
     * @DynamoDBHashKey: Essa annotation diz para o Spring Data que esse atributo será uma Partition key, resumidamente essa será a chave primária dentro da tabela no Dynamo.
     * @DynamoDBAutoGeneratedKey: Essa annotation diz para o Spring Data que deve ser gerado automaticamente o id da tabela.
     */
    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private String id;

    /**
     * @DynamoDBAttribute: Essa annotation diz para o Spring Data que o campos serão tratados como atributos dentro da tabela.
     */
    @DynamoDBAttribute(attributeName = "company_name")
    @JsonProperty("company_name")
    private String companyName;

    @DynamoDBAttribute(attributeName = "company_document_number")
    @JsonProperty("company_document_number")
    private String companyDocumentNumber;

    @DynamoDBAttribute(attributeName = "phone_number")
    @JsonProperty("phone_number")
    private String phoneNumber;

    @DynamoDBAttribute(attributeName = "active")
    @JsonProperty("active")
    private Boolean active;

    @Deprecated
    public Costumer() {
    }

    public Costumer(String companyName, String companyDocumentNumber, String phoneNumber, Boolean active) {
        this.companyName = companyName;
        this.companyDocumentNumber = companyDocumentNumber;
        this.phoneNumber = phoneNumber;
        this.active = active;
    }
}
